name: RASCL_HEAVY
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython=1.79
  - hyphy=2.5.36 
  - raxml-ng=1.0.2 
  - snakemake=7.3.8
  - stephenshank::tn93=1.0.7
  - python-bioext=0.20.4
  - python=3.8
